<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Step 3_accept_tos</name>
   <tag></tag>
   <elementGuidId>7bcc3891-c474-427f-ad75-67ba535fbaa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;accept_tos&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accept_tos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad4282fd-0c4f-4a2e-ba94-fb16f306e04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept_tos</value>
      <webElementGuid>a2ea2c9c-e583-49fb-a58b-2263906d4907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3b16a9d0-c60d-4196-85db-223f2d818b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>00cd6a0a-e964-4f30-a151-92a3b08f158c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accept_tos&quot;)/span[1]/input[1]</value>
      <webElementGuid>1627c7f9-1ce3-42e6-8e69-ec6c217625a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='accept_tos']</value>
      <webElementGuid>8f6c692f-b6b9-4da3-9765-7e06e60976b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='accept_tos']/span/input</value>
      <webElementGuid>cd3b65a3-c6f5-4f20-af72-fbc6c2e04526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>1c358d6c-6001-4ede-b2a0-3fa0c9675c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'accept_tos' and @type = 'checkbox']</value>
      <webElementGuid>6ae03cbd-8d78-4012-bb4e-d1ec9ff9ad25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
