<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your email address_uploader_email</name>
   <tag></tag>
   <elementGuidId>83bd4528-6a19-460a-88b0-0ac73181c5e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploader_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploader_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f00fa12-32d3-428f-8a16-7646fdcdd63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uploader_email</value>
      <webElementGuid>8c92fc93-660e-4245-81e0-f8146d4dfd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2faf299-1912-40da-a76b-287ad43611d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span12</value>
      <webElementGuid>17c4aab0-f2ae-4b5f-8808-bfa098b563b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploader_email</value>
      <webElementGuid>22f885d5-f364-477b-9a6c-0208a187ae74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploader_email&quot;)</value>
      <webElementGuid>37add54a-c467-4845-9215-fcc2b04edca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploader_email']</value>
      <webElementGuid>99ff9b99-5119-4d30-b154-fab06080adf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[2]/input</value>
      <webElementGuid>9d2f1588-bc68-4302-8701-0bbcd7c89386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9607c285-a0e4-45a1-9be4-0c1b6b282548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'uploader_email' and @type = 'text' and @id = 'uploader_email']</value>
      <webElementGuid>b1b62550-bc44-4431-a981-82dbccaf62cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
