<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select a file_upload_file</name>
   <tag></tag>
   <elementGuidId>e85ef082-d3c9-40ea-b80b-35f93cf75f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;upload_file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='upload_file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe51c409-ff7a-4807-915b-8503da8ff64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>upload_file</value>
      <webElementGuid>e47cd074-f1ce-428a-89ec-2b674e12a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>23285a30-d9b0-4dba-96c7-e17a16d1719b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span12</value>
      <webElementGuid>c211023e-6e29-452d-b3f1-58fb2ddbb45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>564036d6-4a48-43ac-8f1a-5cb54ef876be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;row-fluid&quot;]/div[@class=&quot;span12&quot;]/div[@class=&quot;form_file form_label&quot;]/input[@class=&quot;span12&quot;]</value>
      <webElementGuid>e1ca78f5-b380-4029-8105-959db2400a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='upload_file']</value>
      <webElementGuid>7025548f-d7c1-4155-a4ce-f0c0c7a0dd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div/input</value>
      <webElementGuid>e95d4dba-704c-4e83-851a-908ba00b33b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3e277ce8-0051-4cde-be58-c1fedfd46add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'upload_file' and @type = 'file']</value>
      <webElementGuid>b0aae18d-a57e-41f9-b311-8d80512d804c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
